paths:
  docs: docs
  guidelines: guidelines.md
  lessons: lessons.md
  overview: overview.md
  plan: plan.yml
include: ['src/**/*.ts', 'src/**/*.svelte', 'rust_helper/**/*.rs']
exclude: []
technologies: []
commands: {}
