# yaml-language-server: $schema=./schema/project-config-schema.json
paths:
  docs: docs
  guidelines: guidelines.md
  lessons: lessons.md
  overview: overview.md
  plan: plan.yml
include: ['src/**/*.ts', 'src/**/*.svelte', 'rust_helper/**/*.rs']
exclude: []
technologies:
  - name: typescript
  - name: svelte
  - name: rust
commands:
  build: pnpm run build
  test: pnpm run test
  format: pnpm run format
  lint: pnpm run lint
  typecheck: pnpm run check
  generate_types: pnpm exec svelte-kit sync
