/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function minhashPath(path: string): Uint32Array
export declare function minhashText(text: string): Uint32Array
