/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function minhashPath(path: string): Array<number>
export declare function minhashText(text: string): Array<number>
